version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-job_portal}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: npm run start:dev
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      DB_DATABASE: ${POSTGRES_DB:-job_portal}
    ports:
      - '${BACKEND_PORT:-3000}:3000'
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app

  frontend:
    build: ./frontend
    command: npm run dev -- --host 0.0.0.0
    ports:
      - '${FRONTEND_PORT:-5173}:5173'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

volumes:
  db_data:
